M48
; DRILL file KiCad 10.0.5 date 2026-08-30T12:15:25
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-30T12:15:25+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X93.776Y-86.576
T2
X25.0Y-25.0
X25.0Y-98.5
X64.0Y-25.0
X120.0Y-98.5
M30
