M48
; DRILL file KiCad 10.0.5 date 2026-09-10T11:57:11
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-10T11:57:11+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X82.85Y-78.306
T2
X23.5Y-77.0
X24.0Y-25.0
X90.0Y-25.0
X90.0Y-77.0
M30
