M48
; DRILL file KiCad 10.0.5 date 2026-08-31T10:10:10
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-31T10:10:10+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X79.349Y-65.234
T2
X25.0Y-25.0
X25.0Y-85.0
X110.0Y-25.0
X110.0Y-85.0
M30
